server {
        listen 80;
        server_name testp.com;

        resolver 223.5.5.5 119.29.29.29 valid=120s;

        location / {
            set $target_host "";
            set $target_port "";
            set $target_uri "";
            set $target_name "";
            set $fallback_host "";
            set $fallback_port "";
            set $fallback_uri "";
            set $fallback_name "";
            set $target_scheme "";
            set $fallback_scheme "";
            content_by_lua_block {
                local selector = require "demo"
                selector.run()
            }
        }

        location @origin_proxy {
            internal;
            proxy_pass $target_scheme://$target_host:$target_port$target_uri;
            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header Connection "";
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Origin-Factory $target_name;

            proxy_connect_timeout 5;
            proxy_read_timeout 30;

            proxy_intercept_errors on;
            error_page 400 401 403 404 405 408 410 429 500 502 503 504 = @fallback_select;
        }

        location @fallback_select {
            internal;

            content_by_lua_block {
                local selector = require "demo"
                selector.fallback()
            }
        }

        location @fallback_proxy {
            internal;

            if ($fallback_host = "") {
                return 502 "fallback upstream unavailable\n";
            }
            proxy_pass $fallback_scheme://$fallback_host:$fallback_port$fallback_uri;

            proxy_http_version 1.1;
            proxy_set_header Host $host;
            proxy_set_header Connection "";
            proxy_set_header X-Real-IP $remote_addr;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
            proxy_set_header X-Origin-Factory $fallback_name;
            proxy_connect_timeout 5;
            proxy_read_timeout 60;

            proxy_intercept_errors off;
        }
}
